// src/app/layout.js
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Navbar from "../components/Navbar";

export const metadata = {
  title: "Social Thingy",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className="antialiased bg-gradient-to-r from-pink-500 via-red-500 to-yellow-500 text-white">
          <Navbar />
          <main className="flex-1 p-4">
            {children}
          </main>
        </body>
      </html>
    </ClerkProvider>
  );
}